services:
  frontend:
    build:
      context: ./cinema-front
    image: cinema-front-image
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - cinema-network  

  backend:
    build:
      context: ./backend-c2
    image: backend-c2-image
    ports:
     - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-2:3306/cinema_database_docker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cinema-network     

  mysql:
    container_name: mysql-docker-2
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cinema_database_docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-docker-2:/var/lib/mysql
    networks:
      - cinema-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-docker-2:

networks:
  cinema-network: